using ListaComprasApp.ViewModels;
using ListaComprasApp.Services;
using ListaComprasApp.Models;
using System.Globalization;

namespace ListaComprasApp.Views;
public static class ProdutosCatalogo
{
    public static Dictionary<Categoria, List<(string Nome, UnidadeMedida Unidade, string Icone, decimal PrecoMedio)>> ObterProdutosPorCategoria()
    {
        return new Dictionary<Categoria, List<(string, UnidadeMedida, string, decimal)>>
        {
            // ========== FRUTAS E VERDURAS ==========
            [Categoria.FrutasVerduras] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Fruta", UnidadeMedida.Kilo, "🍎", 6.00m),
                ("Abacaxi", UnidadeMedida.Unidade, "🍍", 8.00m),
                ("Abacate", UnidadeMedida.Unidade, "🥑", 7.50m),
                ("Banana Prata", UnidadeMedida.Kilo, "🍌", 4.50m),
                ("Banana Nanica", UnidadeMedida.Kilo, "🍌", 4.00m),
                ("Banana", UnidadeMedida.Kilo, "🍌", 4.50m),
                ("Laranja Pera", UnidadeMedida.Kilo, "🍊", 3.80m),
                ("Laranja Lima", UnidadeMedida.Kilo, "🍊", 4.20m),
                ("Laranja", UnidadeMedida.Kilo, "🍊", 3.80m),
                ("Maçã Fuji", UnidadeMedida.Kilo, "🍎", 6.50m),
                ("Maçã Gala", UnidadeMedida.Kilo, "🍎", 6.00m),
                ("Maçã", UnidadeMedida.Kilo, "🍎", 6.00m),
                ("Mamão Papaya", UnidadeMedida.Unidade, "🍈", 9.00m),
                ("Mamão Formosa", UnidadeMedida.Unidade, "🍈", 8.00m),
                ("Mamão", UnidadeMedida.Unidade, "🍈", 9.00m),
                ("Melancia", UnidadeMedida.Unidade, "🍉", 15.00m),
                ("Melão", UnidadeMedida.Unidade, "🍈", 12.00m),
                ("Morango", UnidadeMedida.Kilo, "🍓", 12.00m),
                ("Uva Verde", UnidadeMedida.Kilo, "🍇", 14.00m),
                ("Uva Roxa", UnidadeMedida.Kilo, "🍇", 15.00m),
                ("Uva", UnidadeMedida.Kilo, "🍇", 14.00m),
                ("Limão Taiti", UnidadeMedida.Kilo, "🍋", 4.50m),
                ("Limão Siciliano", UnidadeMedida.Kilo, "🍋", 5.50m),
                ("Limão", UnidadeMedida.Kilo, "🍋", 4.50m),
                ("Manga Palmer", UnidadeMedida.Kilo, "🥭", 8.00m),
                ("Manga Tommy", UnidadeMedida.Kilo, "🥭", 8.50m),
                ("Manga", UnidadeMedida.Kilo, "🥭", 8.00m),
                ("Pera", UnidadeMedida.Kilo, "🍐", 9.00m),
                ("Kiwi", UnidadeMedida.Kilo, "🥝", 18.00m),
                ("Verdura", UnidadeMedida.Kilo, "🥬", 4.00m),
                ("Alface Americana", UnidadeMedida.Unidade, "🥬", 3.00m),
                ("Alface Crespa", UnidadeMedida.Unidade, "🥬", 2.50m),
                ("Alface", UnidadeMedida.Unidade, "🥬", 2.50m),
                ("Tomate Italiano", UnidadeMedida.Kilo, "🍅", 7.00m),
                ("Tomate Salada", UnidadeMedida.Kilo, "🍅", 6.50m),
                ("Tomate", UnidadeMedida.Kilo, "🍅", 6.50m),
                ("Batata Inglesa", UnidadeMedida.Kilo, "🥔", 4.80m),
                ("Batata Doce", UnidadeMedida.Kilo, "🥔", 5.50m),
                ("Batata", UnidadeMedida.Kilo, "🥔", 4.80m),
                ("Cebola Branca", UnidadeMedida.Kilo, "🧅", 5.20m),
                ("Cebola Roxa", UnidadeMedida.Kilo, "🧅", 6.00m),
                ("Cebola", UnidadeMedida.Kilo, "🧅", 5.20m),
                ("Cenoura", UnidadeMedida.Kilo, "🥕", 4.20m),
                ("Brócolis", UnidadeMedida.Unidade, "🥦", 7.00m),
                ("Couve", UnidadeMedida.Unidade, "🥬", 3.00m),
                ("Repolho Verde", UnidadeMedida.Kilo, "🥬", 3.50m),
                ("Repolho Roxo", UnidadeMedida.Kilo, "🥬", 4.00m),
                ("Repolho", UnidadeMedida.Kilo, "🥬", 3.50m),
                ("Abobrinha", UnidadeMedida.Kilo, "🥒", 5.50m),
                ("Berinjela", UnidadeMedida.Kilo, "🍆", 6.00m),
                ("Pimentão Verde", UnidadeMedida.Kilo, "🫑", 8.00m),
                ("Pimentão Vermelho", UnidadeMedida.Kilo, "🫑", 9.00m),
                ("Pimentão Amarelo", UnidadeMedida.Kilo, "🫑", 10.00m),
                ("Pimentão", UnidadeMedida.Kilo, "🫑", 9.00m),
                ("Pepino", UnidadeMedida.Kilo, "🥒", 4.50m),
                ("Agrião", UnidadeMedida.Unidade, "🌿", 3.50m),
                ("Rúcula", UnidadeMedida.Unidade, "🥬", 4.00m),
                ("Espinafre", UnidadeMedida.Unidade, "🥬", 4.50m),
                ("Mandioca", UnidadeMedida.Kilo, "🥔", 5.00m),
                ("Mandioquinha", UnidadeMedida.Kilo, "🥔", 6.50m),
                ("Beterraba", UnidadeMedida.Kilo, "🥕", 4.80m),
                ("Rabanete", UnidadeMedida.Unidade, "🥕", 3.00m),
                ("Chuchu", UnidadeMedida.Kilo, "🥒", 3.50m),
                ("Abóbora", UnidadeMedida.Kilo, "🎃", 4.00m),
                ("Vagem", UnidadeMedida.Kilo, "🫛", 7.00m),
                ("Quiabo", UnidadeMedida.Kilo, "🫛", 6.50m),
                ("Jiló", UnidadeMedida.Kilo, "🫛", 5.50m),
            },

            // ========== CARNES ==========
            [Categoria.Carnes] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Carne Bovina", UnidadeMedida.Kilo, "🥩", 45.00m),
                ("Picanha", UnidadeMedida.Kilo, "🥩", 89.90m),
                ("Alcatra", UnidadeMedida.Kilo, "🥩", 45.90m),
                ("Filé Mignon", UnidadeMedida.Kilo, "🥩", 79.90m),
                ("Contrafilé", UnidadeMedida.Kilo, "🥩", 52.90m),
                ("Maminha", UnidadeMedida.Kilo, "🥩", 48.90m),
                ("Patinho", UnidadeMedida.Kilo, "🥩", 38.90m),
                ("Coxão Mole", UnidadeMedida.Kilo, "🥩", 36.90m),
                ("Coxão Duro", UnidadeMedida.Kilo, "🥩", 32.90m),
                ("Músculo", UnidadeMedida.Kilo, "🥩", 28.90m),
                ("Acém", UnidadeMedida.Kilo, "🥩", 29.90m),
                ("Lagarto", UnidadeMedida.Kilo, "🥩", 34.90m),
                ("Costela Bovina", UnidadeMedida.Kilo, "🥩", 35.90m),
                ("Carne Moída", UnidadeMedida.Kilo, "🥩", 28.90m),
                ("Frango", UnidadeMedida.Kilo, "🐔", 15.00m),
                ("Frango Inteiro", UnidadeMedida.Kilo, "🐔", 12.90m),
                ("Peito de Frango", UnidadeMedida.Kilo, "🐔", 18.90m),
                ("Coxa e Sobrecoxa", UnidadeMedida.Kilo, "🐔", 14.90m),
                ("Asa de Frango", UnidadeMedida.Kilo, "🐔", 16.90m),
                ("Filé de Frango", UnidadeMedida.Kilo, "🐔", 22.90m),
                ("Carne Suína", UnidadeMedida.Kilo, "🥓", 25.00m),
                ("Pernil de Porco", UnidadeMedida.Kilo, "🥓", 22.90m),
                ("Lombo Suíno", UnidadeMedida.Kilo, "🥓", 28.90m),
                ("Bisteca Suína", UnidadeMedida.Kilo, "🥓", 24.90m),
                ("Costela Suína", UnidadeMedida.Kilo, "🥓", 26.90m),
                ("Bacon", UnidadeMedida.Kilo, "🥓", 38.90m),
                ("Linguiça Calabresa", UnidadeMedida.Kilo, "🌭", 24.90m),
                ("Linguiça Toscana", UnidadeMedida.Kilo, "🌭", 26.90m),
                ("Linguiça de Frango", UnidadeMedida.Kilo, "🌭", 22.90m),
                ("Linguiça", UnidadeMedida.Kilo, "🌭", 24.90m),
                ("Salsicha", UnidadeMedida.Kilo, "🌭", 18.90m),
                ("Presunto", UnidadeMedida.Kilo, "🥓", 32.90m),
                ("Mortadela", UnidadeMedida.Kilo, "🥓", 28.90m),
                ("Peito de Peru", UnidadeMedida.Kilo, "🥓", 42.90m),
                ("Salame", UnidadeMedida.Kilo, "🥓", 38.90m),
            },

            // ========== LATICÍNIOS ==========
            [Categoria.Laticinios] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Leite", UnidadeMedida.Litro, "🥛", 5.50m),
                ("Leite Integral", UnidadeMedida.Litro, "🥛", 5.50m),
                ("Leite Desnatado", UnidadeMedida.Litro, "🥛", 5.80m),
                ("Leite Semi-desnatado", UnidadeMedida.Litro, "🥛", 5.70m),
                ("Leite Zero Lactose", UnidadeMedida.Litro, "🥛", 7.90m),
                ("Iogurte", UnidadeMedida.Unidade, "🥛", 4.50m),
                ("Iogurte Natural", UnidadeMedida.Unidade, "🥛", 4.50m),
                ("Iogurte Grego", UnidadeMedida.Unidade, "🥛", 7.90m),
                ("Iogurte com Frutas", UnidadeMedida.Unidade, "🥛", 5.50m),
                ("Queijo", UnidadeMedida.Kilo, "🧀", 45.00m),
                ("Queijo Mussarela", UnidadeMedida.Kilo, "🧀", 48.90m),
                ("Queijo Prato", UnidadeMedida.Kilo, "🧀", 52.90m),
                ("Queijo Parmesão", UnidadeMedida.Kilo, "🧀", 89.90m),
                ("Queijo Minas", UnidadeMedida.Kilo, "🧀", 45.90m),
                ("Queijo Coalho", UnidadeMedida.Kilo, "🧀", 42.90m),
                ("Queijo Provolone", UnidadeMedida.Kilo, "🧀", 58.90m),
                ("Queijo Cottage", UnidadeMedida.Unidade, "🧀", 12.90m),
                ("Queijo Ricota", UnidadeMedida.Kilo, "🧀", 38.90m),
                ("Queijo Gorgonzola", UnidadeMedida.Kilo, "🧀", 78.90m),
                ("Requeijão", UnidadeMedida.Unidade, "🧈", 12.90m),
                ("Manteiga", UnidadeMedida.Unidade, "🧈", 18.90m),
                ("Manteiga com Sal", UnidadeMedida.Unidade, "🧈", 18.90m),
                ("Manteiga sem Sal", UnidadeMedida.Unidade, "🧈", 19.90m),
                ("Margarina", UnidadeMedida.Unidade, "🧈", 9.90m),
                ("Creme de Leite", UnidadeMedida.Unidade, "🥛", 4.50m),
                ("Leite Condensado", UnidadeMedida.Unidade, "🥛", 7.90m),
                ("Nata", UnidadeMedida.Unidade, "🥛", 8.50m),
                ("Chantilly", UnidadeMedida.Unidade, "🥛", 9.90m),
            },

            // ========== BEBIDAS ==========
            [Categoria.Bebidas] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Refrigerante", UnidadeMedida.Unidade, "🥤", 9.00m),
                ("Coca-Cola 2L", UnidadeMedida.Unidade, "🥤", 9.90m),
                ("Coca-Cola Zero 2L", UnidadeMedida.Unidade, "🥤", 10.50m),
                ("Guaraná 2L", UnidadeMedida.Unidade, "🥤", 8.50m),
                ("Fanta 2L", UnidadeMedida.Unidade, "🥤", 8.90m),
                ("Sprite 2L", UnidadeMedida.Unidade, "🥤", 8.90m),
                ("Pepsi 2L", UnidadeMedida.Unidade, "🥤", 8.50m),
                ("Suco", UnidadeMedida.Litro, "🧃", 12.00m),
                ("Suco de Laranja", UnidadeMedida.Litro, "🧃", 12.90m),
                ("Suco de Uva", UnidadeMedida.Litro, "🧃", 14.90m),
                ("Suco de Maracujá", UnidadeMedida.Litro, "🧃", 13.90m),
                ("Suco de Abacaxi", UnidadeMedida.Litro, "🧃", 12.50m),
                ("Suco em Pó", UnidadeMedida.Unidade, "🧃", 4.50m),
                ("Água", UnidadeMedida.Unidade, "💧", 2.50m),
                ("Água Mineral 1.5L", UnidadeMedida.Unidade, "💧", 2.50m),
                ("Água com Gás", UnidadeMedida.Unidade, "💧", 3.50m),
                ("Água de Coco", UnidadeMedida.Unidade, "🥥", 6.90m),
                ("Cerveja", UnidadeMedida.Unidade, "🍺", 3.50m),
                ("Cerveja Lata", UnidadeMedida.Unidade, "🍺", 3.50m),
                ("Cerveja Long Neck", UnidadeMedida.Unidade, "🍺", 4.50m),
                ("Vinho", UnidadeMedida.Unidade, "🍷", 35.00m),
                ("Vinho Tinto", UnidadeMedida.Unidade, "🍷", 35.00m),
                ("Vinho Branco", UnidadeMedida.Unidade, "🍷", 38.00m),
                ("Energético", UnidadeMedida.Unidade, "⚡", 8.90m),
                ("Chá Gelado", UnidadeMedida.Unidade, "🧃", 5.90m),
                ("Café Líquido", UnidadeMedida.Unidade, "☕", 7.90m),
            },

            // ========== LIMPEZA ==========
            [Categoria.Limpeza] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Produto de Limpeza", UnidadeMedida.Unidade, "🧴", 8.00m),
                ("Detergente", UnidadeMedida.Unidade, "🧴", 2.50m),
                ("Detergente Neutro", UnidadeMedida.Unidade, "🧴", 2.50m),
                ("Detergente Limão", UnidadeMedida.Unidade, "🧴", 2.50m),
                ("Sabão em Pó", UnidadeMedida.Unidade, "📦", 18.90m),
                ("Sabão Líquido", UnidadeMedida.Unidade, "🧴", 22.90m),
                ("Amaciante", UnidadeMedida.Unidade, "🧴", 12.90m),
                ("Água Sanitária", UnidadeMedida.Unidade, "🧴", 6.50m),
                ("Desinfetante", UnidadeMedida.Unidade, "🧴", 8.90m),
                ("Desinfetante Lavanda", UnidadeMedida.Unidade, "🧴", 8.90m),
                ("Esponja de Limpeza", UnidadeMedida.Unidade, "🧽", 3.50m),
                ("Pano de Chão", UnidadeMedida.Unidade, "🧹", 12.00m),
                ("Pano de Prato", UnidadeMedida.Unidade, "🧹", 8.00m),
                ("Vassoura", UnidadeMedida.Unidade, "🧹", 25.00m),
                ("Rodo", UnidadeMedida.Unidade, "🧹", 18.00m),
                ("Saco de Lixo", UnidadeMedida.Pacote, "🗑️", 15.90m),
                ("Saco de Lixo 50L", UnidadeMedida.Pacote, "🗑️", 15.90m),
                ("Saco de Lixo 100L", UnidadeMedida.Pacote, "🗑️", 22.90m),
                ("Álcool", UnidadeMedida.Litro, "🧴", 14.90m),
                ("Álcool 70%", UnidadeMedida.Litro, "🧴", 14.90m),
                ("Álcool em Gel", UnidadeMedida.Unidade, "🧴", 12.90m),
                ("Limpa Vidros", UnidadeMedida.Unidade, "🧴", 9.90m),
                ("Multiuso", UnidadeMedida.Unidade, "🧴", 11.90m),
                ("Sabão em Barra", UnidadeMedida.Unidade, "🧼", 4.50m),
                ("Luva de Limpeza", UnidadeMedida.Unidade, "🧤", 8.90m),
                ("Balde", UnidadeMedida.Unidade, "🪣", 18.00m),
            },

            // ========== PADARIA ==========
            [Categoria.Padaria] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Pão", UnidadeMedida.Kilo, "🍞", 18.00m),
                ("Pão Francês", UnidadeMedida.Kilo, "🍞", 18.90m),
                ("Pão de Forma", UnidadeMedida.Unidade, "🍞", 8.90m),
                ("Pão de Forma Integral", UnidadeMedida.Unidade, "🍞", 10.90m),
                ("Pão Integral", UnidadeMedida.Unidade, "🍞", 12.90m),
                ("Pão de Queijo", UnidadeMedida.Kilo, "🧀", 32.90m),
                ("Pão de Alho", UnidadeMedida.Unidade, "🧄", 15.90m),
                ("Pão Sírio", UnidadeMedida.Pacote, "🍞", 9.90m),
                ("Pão de Hot Dog", UnidadeMedida.Pacote, "🍞", 8.90m),
                ("Pão de Hambúrguer", UnidadeMedida.Pacote, "🍞", 9.90m),
                ("Croissant", UnidadeMedida.Unidade, "🥐", 6.50m),
                ("Bisnaguinha", UnidadeMedida.Pacote, "🍞", 9.90m),
                ("Bolo", UnidadeMedida.Unidade, "🎂", 25.00m),
                ("Bolo Simples", UnidadeMedida.Unidade, "🎂", 25.00m),
                ("Bolo de Chocolate", UnidadeMedida.Unidade, "🎂", 28.00m),
                ("Torta", UnidadeMedida.Unidade, "🥧", 35.00m),
                ("Torta Salgada", UnidadeMedida.Unidade, "🥧", 35.00m),
                ("Torta Doce", UnidadeMedida.Unidade, "🥧", 38.00m),
                ("Sonho", UnidadeMedida.Unidade, "🍩", 7.00m),
                ("Rosquinha", UnidadeMedida.Unidade, "🍩", 6.50m),
            },

            // ========== CONGELADOS ==========
            [Categoria.Congelados] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Congelado", UnidadeMedida.Unidade, "🧊", 20.00m),
                ("Pizza Congelada", UnidadeMedida.Unidade, "🍕", 18.90m),
                ("Pizza Mussarela", UnidadeMedida.Unidade, "🍕", 18.90m),
                ("Pizza Calabresa", UnidadeMedida.Unidade, "🍕", 19.90m),
                ("Lasanha Congelada", UnidadeMedida.Unidade, "🍝", 22.90m),
                ("Hambúrguer Congelado", UnidadeMedida.Pacote, "🍔", 24.90m),
                ("Batata Congelada", UnidadeMedida.Pacote, "🍟", 16.90m),
                ("Batata Frita Congelada", UnidadeMedida.Pacote, "🍟", 16.90m),
                ("Batata Palito", UnidadeMedida.Pacote, "🍟", 17.90m),
                ("Sorvete", UnidadeMedida.Unidade, "🍦", 28.00m),
                ("Sorvete 2L", UnidadeMedida.Unidade, "🍦", 28.90m),
                ("Picolé", UnidadeMedida.Unidade, "🍡", 3.50m),
                ("Nuggets", UnidadeMedida.Pacote, "🍗", 19.90m),
                ("Polpa de Fruta", UnidadeMedida.Unidade, "🧊", 12.90m),
                ("Peixe Congelado", UnidadeMedida.Kilo, "🐟", 32.90m),
                ("Camarão Congelado", UnidadeMedida.Kilo, "🦐", 68.90m),
                ("Frutos do Mar", UnidadeMedida.Kilo, "🦐", 55.90m),
                ("Vegetais Congelados", UnidadeMedida.Pacote, "🥦", 14.90m),
            },

            // ========== HIGIENE ==========
            [Categoria.Higiene] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Produto de Higiene", UnidadeMedida.Unidade, "🧴", 10.00m),
                ("Sabonete", UnidadeMedida.Unidade, "🧼", 3.50m),
                ("Sabonete Líquido", UnidadeMedida.Unidade, "🧴", 12.90m),
                ("Shampoo", UnidadeMedida.Unidade, "🧴", 15.90m),
                ("Condicionador", UnidadeMedida.Unidade, "🧴", 16.90m),
                ("Creme de Pentear", UnidadeMedida.Unidade, "🧴", 14.90m),
                ("Pasta de Dente", UnidadeMedida.Unidade, "🪥", 8.90m),
                ("Escova de Dente", UnidadeMedida.Unidade, "🪥", 12.90m),
                ("Fio Dental", UnidadeMedida.Unidade, "🦷", 9.90m),
                ("Enxaguante Bucal", UnidadeMedida.Unidade, "🧴", 18.90m),
                ("Desodorante", UnidadeMedida.Unidade, "🧴", 14.90m),
                ("Desodorante Roll-on", UnidadeMedida.Unidade, "🧴", 16.90m),
                ("Desodorante Aerosol", UnidadeMedida.Unidade, "🧴", 14.90m),
                ("Papel Higiênico", UnidadeMedida.Pacote, "🧻", 22.90m),
                ("Papel Toalha", UnidadeMedida.Unidade, "🧻", 12.90m),
                ("Absorvente", UnidadeMedida.Pacote, "🩹", 15.90m),
                ("Sabonete Íntimo", UnidadeMedida.Unidade, "🧴", 18.90m),
                ("Aparelho de Barbear", UnidadeMedida.Unidade, "🪒", 22.90m),
                ("Espuma de Barbear", UnidadeMedida.Unidade, "🧴", 16.90m),
                ("Lenço Umedecido", UnidadeMedida.Pacote, "🧻", 14.90m),
                ("Cotonete", UnidadeMedida.Pacote, "🧴", 8.90m),
                ("Algodão", UnidadeMedida.Pacote, "🧴", 9.90m),
            },

            // ========== ALIMENTOS BÁSICOS ==========
            [Categoria.AlimentosBasicos] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Alimento Básico", UnidadeMedida.Kilo, "🍚", 6.00m),
                ("Arroz", UnidadeMedida.Kilo, "🍚", 5.50m),
                ("Arroz Branco", UnidadeMedida.Kilo, "🍚", 5.50m),
                ("Arroz Integral", UnidadeMedida.Kilo, "🍚", 7.90m),
                ("Arroz Parboilizado", UnidadeMedida.Kilo, "🍚", 6.50m),
                ("Feijão", UnidadeMedida.Kilo, "🫘", 8.90m),
                ("Feijão Preto", UnidadeMedida.Kilo, "🫘", 8.90m),
                ("Feijão Carioca", UnidadeMedida.Kilo, "🫘", 8.50m),
                ("Macarrão", UnidadeMedida.Unidade, "🍝", 4.50m),
                ("Macarrão Espaguete", UnidadeMedida.Unidade, "🍝", 4.50m),
                ("Macarrão Parafuso", UnidadeMedida.Unidade, "🍝", 4.90m),
                ("Macarrão Penne", UnidadeMedida.Unidade, "🍝", 5.50m),
                ("Macarrão Integral", UnidadeMedida.Unidade, "🍝", 6.90m),
                ("Farinha", UnidadeMedida.Kilo, "🌾", 4.50m),
                ("Farinha de Trigo", UnidadeMedida.Kilo, "🌾", 4.50m),
                ("Farinha de Mandioca", UnidadeMedida.Kilo, "🌾", 6.90m),
                ("Farinha de Milho", UnidadeMedida.Kilo, "🌾", 5.50m),
                ("Açúcar", UnidadeMedida.Kilo, "🍬", 4.90m),
                ("Açúcar Cristal", UnidadeMedida.Kilo, "🍬", 4.90m),
                ("Açúcar Refinado", UnidadeMedida.Kilo, "🍬", 5.50m),
                ("Açúcar Mascavo", UnidadeMedida.Kilo, "🍬", 8.90m),
                ("Sal", UnidadeMedida.Kilo, "🧂", 2.50m),
                ("Sal Refinado", UnidadeMedida.Kilo, "🧂", 2.50m),
                ("Sal Grosso", UnidadeMedida.Kilo, "🧂", 3.50m),
                ("Óleo", UnidadeMedida.Unidade, "🛢️", 8.90m),
                ("Óleo de Soja", UnidadeMedida.Unidade, "🛢️", 8.90m),
                ("Óleo de Girassol", UnidadeMedida.Unidade, "🛢️", 12.90m),
                ("Azeite", UnidadeMedida.Unidade, "🫒", 28.90m),
                ("Azeite Extra Virgem", UnidadeMedida.Unidade, "🫒", 35.90m),
                ("Vinagre", UnidadeMedida.Unidade, "🍶", 4.50m),
                ("Vinagre de Álcool", UnidadeMedida.Unidade, "🍶", 4.50m),
                ("Vinagre de Maçã", UnidadeMedida.Unidade, "🍶", 8.90m),
                ("Aveia", UnidadeMedida.Kilo, "🌾", 12.90m),
                ("Granola", UnidadeMedida.Kilo, "🥣", 18.90m),
            },

            // ========== ENLATADOS E CONSERVAS ==========
            [Categoria.EnlatadosConservas] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Enlatado", UnidadeMedida.Unidade, "🥫", 5.00m),
                ("Molho de Tomate", UnidadeMedida.Unidade, "🥫", 3.90m),
                ("Extrato de Tomate", UnidadeMedida.Unidade, "🥫", 4.50m),
                ("Milho em Conserva", UnidadeMedida.Unidade, "🥫", 4.90m),
                ("Ervilha em Conserva", UnidadeMedida.Unidade, "🥫", 4.50m),
                ("Atum em Lata", UnidadeMedida.Unidade, "🥫", 8.90m),
                ("Sardinha em Lata", UnidadeMedida.Unidade, "🥫", 6.90m),
                ("Azeitona", UnidadeMedida.Unidade, "🫒", 12.90m),
                ("Azeitona Verde", UnidadeMedida.Unidade, "🫒", 12.90m),
                ("Azeitona Preta", UnidadeMedida.Unidade, "🫒", 14.90m),
                ("Palmito", UnidadeMedida.Unidade, "🥫", 18.90m),
                ("Milho Verde", UnidadeMedida.Unidade, "🌽", 4.90m),
                ("Cogumelo em Conserva", UnidadeMedida.Unidade, "🥫", 14.90m),
                ("Picles", UnidadeMedida.Unidade, "🥒", 9.90m),
                ("Seleta de Legumes", UnidadeMedida.Unidade, "🥫", 6.90m),
                ("Pêssego em Calda", UnidadeMedida.Unidade, "🥫", 12.90m),
                ("Leite em Pó", UnidadeMedida.Unidade, "🥛", 32.90m),
            },

            // ========== BISCOITOS E SNACKS ==========
            [Categoria.BiscoitosSnacks] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Biscoito", UnidadeMedida.Unidade, "🍪", 5.00m),
                ("Biscoito Maria", UnidadeMedida.Unidade, "🍪", 4.50m),
                ("Biscoito Cream Cracker", UnidadeMedida.Unidade, "🍪", 5.90m),
                ("Biscoito de Chocolate", UnidadeMedida.Unidade, "🍪", 6.90m),
                ("Biscoito Recheado", UnidadeMedida.Unidade, "🍪", 4.90m),
                ("Biscoito Wafer", UnidadeMedida.Unidade, "🍪", 3.90m),
                ("Biscoito Integral", UnidadeMedida.Unidade, "🍪", 7.90m),
                ("Torrada", UnidadeMedida.Unidade, "🍞", 8.90m),
                ("Salgadinho", UnidadeMedida.Unidade, "🥨", 6.50m),
                ("Salgadinho de Milho", UnidadeMedida.Unidade, "🌽", 6.50m),
                ("Batata Chips", UnidadeMedida.Unidade, "🥔", 8.90m),
                ("Pipoca de Micro-ondas", UnidadeMedida.Unidade, "🍿", 7.90m),
                ("Amendoim", UnidadeMedida.Kilo, "🥜", 18.90m),
                ("Castanha", UnidadeMedida.Kilo, "🌰", 45.90m),
                ("Mix de Castanhas", UnidadeMedida.Kilo, "🥜", 52.90m),
            },

            // ========== DOCES E SOBREMESAS ==========
            [Categoria.DocesSobremesas] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Doce", UnidadeMedida.Unidade, "🍫", 8.00m),
                ("Chocolate", UnidadeMedida.Unidade, "🍫", 8.90m),
                ("Chocolate ao Leite", UnidadeMedida.Unidade, "🍫", 8.90m),
                ("Chocolate Branco", UnidadeMedida.Unidade, "🍫", 9.90m),
                ("Chocolate Meio Amargo", UnidadeMedida.Unidade, "🍫", 10.90m),
                ("Bombom", UnidadeMedida.Unidade, "🍬", 12.90m),
                ("Bala", UnidadeMedida.Pacote, "🍬", 4.90m),
                ("Chiclete", UnidadeMedida.Pacote, "🍬", 3.90m),
                ("Pirulito", UnidadeMedida.Unidade, "🍭", 1.50m),
                ("Gelatina", UnidadeMedida.Unidade, "🍮", 2.90m),
                ("Pudim Pronto", UnidadeMedida.Unidade, "🍮", 8.90m),
                ("Mousse", UnidadeMedida.Unidade, "🍮", 9.90m),
                ("Doce de Leite", UnidadeMedida.Unidade, "🍯", 12.90m),
                ("Geleia", UnidadeMedida.Unidade, "🍯", 9.90m),
                ("Geleia de Morango", UnidadeMedida.Unidade, "🍯", 9.90m),
                ("Geleia de Uva", UnidadeMedida.Unidade, "🍯", 10.90m),
                ("Mel", UnidadeMedida.Unidade, "🍯", 28.90m),
                ("Paçoca", UnidadeMedida.Unidade, "🥜", 5.90m),
                ("Pé de Moleque", UnidadeMedida.Unidade, "🥜", 4.90m),
            },

            // ========== TEMPEROS E CONDIMENTOS ==========
            [Categoria.TemperoCondimentos] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Tempero", UnidadeMedida.Unidade, "🧂", 4.00m),
                ("Alho", UnidadeMedida.Kilo, "🧄", 28.90m),
                ("Cebola em Pó", UnidadeMedida.Unidade, "🧅", 6.90m),
                ("Alho em Pó", UnidadeMedida.Unidade, "🧄", 7.90m),
                ("Cominho", UnidadeMedida.Unidade, "🧂", 5.90m),
                ("Páprica", UnidadeMedida.Unidade, "🌶️", 8.90m),
                ("Orégano", UnidadeMedida.Unidade, "🌿", 4.90m),
                ("Manjericão", UnidadeMedida.Unidade, "🌿", 6.90m),
                ("Salsinha", UnidadeMedida.Unidade, "🌿", 3.50m),
                ("Cebolinha", UnidadeMedida.Unidade, "🌿", 3.50m),
                ("Pimenta do Reino", UnidadeMedida.Unidade, "🌶️", 9.90m),
                ("Pimenta Calabresa", UnidadeMedida.Unidade, "🌶️", 7.90m),
                ("Colorau", UnidadeMedida.Unidade, "🌶️", 5.50m),
                ("Curry", UnidadeMedida.Unidade, "🍛", 12.90m),
                ("Canela em Pó", UnidadeMedida.Unidade, "🧂", 8.90m),
                ("Cravo", UnidadeMedida.Unidade, "🧂", 9.90m),
                ("Noz Moscada", UnidadeMedida.Unidade, "🧂", 11.90m),
                ("Louro", UnidadeMedida.Unidade, "🌿", 4.50m),
                ("Caldo de Carne", UnidadeMedida.Unidade, "🧂", 3.50m),
                ("Caldo de Galinha", UnidadeMedida.Unidade, "🧂", 3.50m),
                ("Tempero Completo", UnidadeMedida.Unidade, "🧂", 6.90m),
                ("Mostarda", UnidadeMedida.Unidade, "🧂", 5.90m),
                ("Maionese", UnidadeMedida.Unidade, "🥫", 8.90m),
                ("Ketchup", UnidadeMedida.Unidade, "🥫", 6.90m),
                ("Shoyu", UnidadeMedida.Unidade, "🥫", 12.90m),
                ("Molho Inglês", UnidadeMedida.Unidade, "🥫", 9.90m),
                ("Molho de Pimenta", UnidadeMedida.Unidade, "🌶️", 7.90m),
            },

            // ========== CAFÉS E CHÁS ==========
            [Categoria.CafesChas] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Café", UnidadeMedida.Unidade, "☕", 18.00m),
                ("Café Torrado e Moído", UnidadeMedida.Unidade, "☕", 18.90m),
                ("Café em Grão", UnidadeMedida.Unidade, "☕", 32.90m),
                ("Café Solúvel", UnidadeMedida.Unidade, "☕", 22.90m),
                ("Café Descafeinado", UnidadeMedida.Unidade, "☕", 24.90m),
                ("Chá", UnidadeMedida.Unidade, "🍵", 8.00m),
                ("Chá Preto", UnidadeMedida.Unidade, "🍵", 12.90m),
                ("Chá Verde", UnidadeMedida.Unidade, "🍵", 14.90m),
                ("Chá de Camomila", UnidadeMedida.Unidade, "🍵", 9.90m),
                ("Chá de Hortelã", UnidadeMedida.Unidade, "🍵", 9.90m),
                ("Chá Misto", UnidadeMedida.Unidade, "🍵", 11.90m),
                ("Achocolatado em Pó", UnidadeMedida.Unidade, "☕", 14.90m),
                ("Capuccino", UnidadeMedida.Unidade, "☕", 18.90m),
            },

            // ========== BEBÊ E INFANTIL ==========
            [Categoria.BebeInfantil] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Produto Infantil", UnidadeMedida.Unidade, "🍼", 25.00m),
                ("Fralda", UnidadeMedida.Pacote, "🍼", 42.90m),
                ("Fralda RN", UnidadeMedida.Pacote, "🍼", 38.90m),
                ("Fralda P", UnidadeMedida.Pacote, "🍼", 42.90m),
                ("Fralda M", UnidadeMedida.Pacote, "🍼", 45.90m),
                ("Fralda G", UnidadeMedida.Pacote, "🍼", 48.90m),
                ("Lenço Umedecido", UnidadeMedida.Pacote, "🧻", 14.90m),
                ("Leite em Pó Infantil", UnidadeMedida.Unidade, "🍼", 52.90m),
                ("Papinha", UnidadeMedida.Unidade, "🍼", 8.90m),
                ("Papinha de Frutas", UnidadeMedida.Unidade, "🍼", 8.90m),
                ("Papinha Salgada", UnidadeMedida.Unidade, "🍼", 9.90m),
                ("Mamadeira", UnidadeMedida.Unidade, "🍼", 28.90m),
                ("Chupeta", UnidadeMedida.Unidade, "🍼", 18.90m),
                ("Shampoo Infantil", UnidadeMedida.Unidade, "🧴", 16.90m),
                ("Sabonete Infantil", UnidadeMedida.Unidade, "🧼", 8.90m),
                ("Pomada para Assadura", UnidadeMedida.Unidade, "🧴", 22.90m),
            },

            // ========== PET SHOP ==========
            [Categoria.PetShop] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Produto Pet", UnidadeMedida.Kilo, "🐕", 35.00m),
                ("Ração para Cães", UnidadeMedida.Kilo, "🐕", 38.90m),
                ("Ração para Gatos", UnidadeMedida.Kilo, "🐈", 42.90m),
                ("Areia para Gatos", UnidadeMedida.Unidade, "🐈", 28.90m),
                ("Petisco para Cães", UnidadeMedida.Unidade, "🦴", 12.90m),
                ("Petisco para Gatos", UnidadeMedida.Unidade, "🐟", 14.90m),
                ("Shampoo para Cães", UnidadeMedida.Unidade, "🧴", 22.90m),
                ("Antipulgas", UnidadeMedida.Unidade, "💊", 48.90m),
            },

            // ========== UTILIDADES DOMÉSTICAS ==========
            [Categoria.UtilidadesDomesticas] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Utensílio", UnidadeMedida.Unidade, "🥘", 25.00m),
                ("Panela", UnidadeMedida.Unidade, "🥘", 89.90m),
                ("Panela de Pressão", UnidadeMedida.Unidade, "🥘", 189.90m),
                ("Frigideira", UnidadeMedida.Unidade, "🍳", 68.90m),
                ("Jogo de Panelas", UnidadeMedida.Unidade, "🥘", 389.90m),
                ("Copo", UnidadeMedida.Unidade, "🥤", 12.90m),
                ("Jogo de Copos", UnidadeMedida.Unidade, "🥤", 48.90m),
                ("Prato", UnidadeMedida.Unidade, "🍽️", 18.90m),
                ("Jogo de Pratos", UnidadeMedida.Unidade, "🍽️", 89.90m),
                ("Tigela", UnidadeMedida.Unidade, "🥣", 22.90m),
                ("Bowl", UnidadeMedida.Unidade, "🥣", 28.90m),
                ("Talheres", UnidadeMedida.Unidade, "🍴", 8.90m),
                ("Faca", UnidadeMedida.Unidade, "🔪", 32.90m),
                ("Garfo", UnidadeMedida.Unidade, "🍴", 12.90m),
                ("Colher", UnidadeMedida.Unidade, "🥄", 12.90m),
                ("Jogo de Talheres", UnidadeMedida.Unidade, "🍴", 78.90m),
                ("Faqueiro", UnidadeMedida.Unidade, "🍴", 189.90m),
                ("Tábua de Corte", UnidadeMedida.Unidade, "🔪", 38.90m),
                ("Forma de Bolo", UnidadeMedida.Unidade, "🍰", 28.90m),
                ("Assadeira", UnidadeMedida.Unidade, "🥘", 45.90m),
                ("Peneira", UnidadeMedida.Unidade, "🥘", 18.90m),
                ("Escorredor de Macarrão", UnidadeMedida.Unidade, "🥘", 22.90m),
                ("Ralador", UnidadeMedida.Unidade, "🔪", 24.90m),
                ("Espremedor de Alho", UnidadeMedida.Unidade, "🧄", 16.90m),
                ("Abridor de Latas", UnidadeMedida.Unidade, "🥫", 14.90m),
                ("Saca Rolhas", UnidadeMedida.Unidade, "🍷", 22.90m),
                ("Jarra", UnidadeMedida.Unidade, "🫙", 32.90m),
                ("Garrafa Térmica", UnidadeMedida.Unidade, "🫙", 58.90m),
                ("Pote de Vidro", UnidadeMedida.Unidade, "🫙", 18.90m),
                ("Pote Plástico", UnidadeMedida.Unidade, "📦", 12.90m),
                ("Jogo de Potes", UnidadeMedida.Unidade, "📦", 48.90m),
                ("Papel Alumínio", UnidadeMedida.Unidade, "📦", 14.90m),
                ("Papel Filme", UnidadeMedida.Unidade, "📦", 12.90m),
                ("Papel Manteiga", UnidadeMedida.Unidade, "📦", 9.90m),
                ("Guardanapo", UnidadeMedida.Pacote, "🧻", 8.90m),
                ("Toalha de Mesa", UnidadeMedida.Unidade, "🧺", 45.90m),
                ("Pano de Prato", UnidadeMedida.Unidade, "🧹", 12.90m),
            },

            // ========== DESCARTÁVEIS ==========
            [Categoria.Descartaveis] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Descartável", UnidadeMedida.Pacote, "🥤", 12.00m),
                ("Copo Descartável", UnidadeMedida.Pacote, "🥤", 8.90m),
                ("Prato Descartável", UnidadeMedida.Pacote, "🍽️", 12.90m),
                ("Talher Descartável", UnidadeMedida.Pacote, "🍴", 9.90m),
                ("Guardanapo", UnidadeMedida.Pacote, "🧻", 6.90m),
                ("Canudo", UnidadeMedida.Pacote, "🥤", 5.90m),
                ("Toalha de Mesa Descartável", UnidadeMedida.Unidade, "🧺", 14.90m),
            },

            // ========== HORTIFRUTI ESPECIAIS ==========
            [Categoria.HortifrutiEspeciais] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Produto Orgânico", UnidadeMedida.Kilo, "🌿", 12.00m),
                ("Alface Orgânica", UnidadeMedida.Unidade, "🥬", 5.50m),
                ("Tomate Orgânico", UnidadeMedida.Kilo, "🍅", 12.90m),
                ("Cenoura Orgânica", UnidadeMedida.Kilo, "🥕", 9.90m),
                ("Batata Orgânica", UnidadeMedida.Kilo, "🥔", 8.90m),
                ("Maçã Orgânica", UnidadeMedida.Kilo, "🍎", 14.90m),
                ("Banana Orgânica", UnidadeMedida.Kilo, "🍌", 9.90m),
                ("Gengibre", UnidadeMedida.Kilo, "🌿", 18.90m),
                ("Açafrão", UnidadeMedida.Kilo, "🌿", 32.90m),
                ("Hortelã", UnidadeMedida.Unidade, "🌿", 4.50m),
                ("Coentro", UnidadeMedida.Unidade, "🌿", 3.50m),
                ("Manjericão Fresco", UnidadeMedida.Unidade, "🌿", 6.90m),
                ("Alecrim", UnidadeMedida.Unidade, "🌿", 5.90m),
            },

            // ========== COMIDAS PRONTAS ==========
            [Categoria.ComidasProntas] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Comida Pronta", UnidadeMedida.Kilo, "🍕", 28.00m),
                ("Frango Assado", UnidadeMedida.Unidade, "🍗", 32.90m),
                ("Salada Pronta", UnidadeMedida.Kilo, "🥗", 22.90m),
                ("Sushi", UnidadeMedida.Unidade, "🍣", 38.90m),
                ("Pizza Pronta", UnidadeMedida.Unidade, "🍕", 45.00m),
                ("Lasanha Pronta", UnidadeMedida.Unidade, "🍝", 28.90m),
                ("Sanduíche Natural", UnidadeMedida.Unidade, "🥪", 12.90m),
                ("Marmita", UnidadeMedida.Unidade, "🍱", 24.90m),
            },

            // ========== FARMÁCIA ==========
            [Categoria.Farmacia] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Medicamento", UnidadeMedida.Unidade, "💊", 18.00m),
                ("Vitamina C", UnidadeMedida.Unidade, "💊", 24.90m),
                ("Complexo B", UnidadeMedida.Unidade, "💊", 32.90m),
                ("Multivitamínico", UnidadeMedida.Unidade, "💊", 48.90m),
                ("Dipirona", UnidadeMedida.Unidade, "💊", 12.90m),
                ("Paracetamol", UnidadeMedida.Unidade, "💊", 14.90m),
                ("Antigripal", UnidadeMedida.Unidade, "💊", 22.90m),
                ("Band-Aid", UnidadeMedida.Unidade, "🩹", 8.90m),
                ("Termômetro", UnidadeMedida.Unidade, "🌡️", 38.90m),
                ("Álcool em Gel", UnidadeMedida.Unidade, "🧴", 12.90m),
            },

            // ========== FESTAS E DECORAÇÃO ==========
            [Categoria.FestasDecoracao] = new List<(string, UnidadeMedida, string, decimal)>
            {
                ("Item de Festa", UnidadeMedida.Unidade, "🎉", 15.00m),
                ("Vela de Aniversário", UnidadeMedida.Pacote, "🕯️", 8.90m),
                ("Balão", UnidadeMedida.Pacote, "🎈", 12.90m),
                ("Faixa de Feliz Aniversário", UnidadeMedida.Unidade, "🎉", 18.90m),
                ("Prato Temático", UnidadeMedida.Pacote, "🍽️", 16.0m)
            }
        };
    } }